spring:
  datasource:
    url: jdbc:mysql://localhost:3367/SpringCloud_Sell?characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.0.198
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.0.198
    port: 6379
