eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanzi88912/SpringCloud-Sell.git
          username: hanzi88912
          password: WOSHIhanzi@163
  rabbitmq:
    host: 192.168.0.198
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
